### ISSUE TITLE
Refresh Data with source set to "Steam" fails

### ISSUE THREAD

**Issue by sunsetHue** [Lacro59/playnite-systemchecker-plugin#44]
## Bug Description
Attempting to use the SystemChecker refresh data when the selected game has the source field set to "Steam" fails and throws an error.

## To Reproduce
1. Add new game
2. Set source field to "Steam"
3. Refresh data with SystemChecker
4. Fails with error

## Extensions log
```
31-05 00:13:41.074|INFO |SystemChecker#PluginDatabaseObject`4:Try find with PCGamingWikiRequierements for Project Zomboid
31-05 00:13:41.082|ERROR|SystemChecker#Common:Error on GetWeb()|G:\GitHub\Lacro59\playnite-systemchecker-plugin\source\Services\SystemCheckerDatabase.cs|105
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at SystemChecker.Clients.PCGamingWikiRequierements.GetRequirements(Game game) in G:\GitHub\Lacro59\playnite-systemchecker-plugin\source\Clients\PCGamingWikiRequierements.cs:line 61
   at SystemChecker.Services.SystemCheckerDatabase.GetWeb(Guid Id) in G:\GitHub\Lacro59\playnite-systemchecker-plugin\source\Services\SystemCheckerDatabase.cs:line 105
```

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-systemchecker-plugin/commit/e5701deddb3490f3dfee4d2a26e5fb2928963e8a
