### ISSUE TITLE
"The Device is not Ready"

### ISSUE THREAD

**Issue by shakeyourbunny** [Lacro59/playnite-systemchecker-plugin#5]
(in my case) it only displays "The device is not ready"(?).
````
2020-08-14 16:42:55.6680|ERROR:Failed to execute extension function.System.IO.IOException: The device is not ready.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIODriveError(String driveName, Int32 errorCode)
   at System.IO.DriveInfo.get_VolumeLabel()
   at SystemChecker.Clients.SystemApi.GetInfoDisks() in H:\Lacro59\playnite-systemchecker-plugin\Clients\SystemApi.cs:line 167
   at SystemChecker.Clients.SystemApi.GetInfo() in H:\Lacro59\playnite-systemchecker-plugin\Clients\SystemApi.cs:line 49
   at SystemChecker.Views.SystemCheckerGameView..ctor(String PluginUserDataPath, Game GameSelected) in H:\Lacro59\playnite-systemchecker-plugin\Views\SystemCheckerGameView.xaml.cs:line 59
   at SystemChecker.SystemChecker.<GetFunctions>b__23_0() in H:\Lacro59\playnite-systemchecker-plugin\SystemChecker.cs:line 74
   at Playnite.SDK.ExtensionFunction.Invoke()
   at Playnite.Plugins.ExtensionFactory.InvokeExtension(ExtensionFunction function, Exception& error) in E:\Devel\Playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 415
````
My guess it tries to read the Volume Labels and crashes if there are drives without them?

**Comment by shakeyourbunny** [comment]
Note that my currently logged in user is a standard user and has no administrative or superuser rights.
